### ISSUE TITLE
Support python3-is-not-python

### ISSUE THREAD

**Issue by mhasself** [arahlin/qpoint#3]
I am trying to integrate qpoint into a Docker container.  In our base:
- `python` is python2, not python3.
- numpy and astropy will be installed and ready in the python3 system, not python2.

The problem is that src/make_iers_bulletin_a_dot_c.py is invoked with `python`, and I need it to be invoked with `python3`.

Ideally (?) setup.py would cause that script to be launched with the same interpreter that was used to launch setup.py.  Alternately, if src/Makefile used the `$(PYTHON)` make variable instead of `python` that would be good enough for my purposes!

[build_log.txt](https://github.com/arahlin/qpoint/files/5683252/build_log.txt)

**Comment by arahlin** [comment]
Good catch!  I've implemented a fix that should pass the interpreter path correctly to `make` from `setup.py` and vice versa.

Closed via 40aff7d
